id: P009376
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W17169
  title: འཇིགས་བྱེད་ཀྱི་བསྐྱེད་རྫོགས་ཀྱི་རྣམ་གཞག
  author: ''
  volumes:
    f4c934e70c044f0f98bc5f37a794eab2:
      image_group_id: I0871
      title: ''
      volume_number: 1
      total_pages: 614
      base_file: v001.txt
